import Foundation

/// Company join codes (`WORD-####`, e.g. `BREW-4821`), as generated by `generateJoinCode()` in
/// @workmode/shared (4–5 letters) and accepted by the API's `companyCodeSchema` (3–8 letters).
public enum CompanyCode {
    public static let minLetters = 3
    public static let maxLetters = 8
    public static let digitCount = 4
    /// Placeholder shown in the text field.
    public static let placeholder = "BREW-4821"

    /// Canonicalises typed input: trims, upper-cases and accepts `brew4821`, `brew 4821`, `BREW-4821`,
    /// `brew_4821`, `brew--4821` → `BREW-4821`. Total: input that cannot be made canonical is returned
    /// upper-cased with separators removed so it can be echoed back in an error.
    public static func normalise(_ input: String) -> String {
        let compact = String(input.uppercased().unicodeScalars.filter { !isSeparator($0) })
        let letters = compact.prefix { isASCIILetter($0) }
        let rest = compact.dropFirst(letters.count)
        if (minLetters...maxLetters).contains(letters.count),
           rest.count == digitCount,
           rest.allSatisfy(isASCIIDigit) {
            return "\(letters)-\(rest)"
        }
        return compact
    }

    /// True when `code` is already canonical (run `normalise` first for user input).
    public static func isValid(_ code: String) -> Bool {
        let parts = code.split(separator: "-", omittingEmptySubsequences: false)
        guard parts.count == 2 else { return false }
        let letters = parts[0]
        let digits = parts[1]
        return (minLetters...maxLetters).contains(letters.count)
            && letters.allSatisfy(isASCIIUppercaseLetter)
            && digits.count == digitCount
            && digits.allSatisfy(isASCIIDigit)
    }

    /// Live formatting for the company-code text field ("XXXX-0000"): upper-cases letters, drops anything
    /// that cannot appear at the cursor's position, inserts the hyphen once digits start and caps the length.
    ///   "brew"      → "BREW"
    ///   "brew4"     → "BREW-4"
    ///   "BREW-48219"→ "BREW-4821"
    ///   "br3"       → "BR"        (digits are only accepted after at least three letters)
    public static func formatAsTyped(_ input: String) -> String {
        var letters = ""
        var digits = ""
        for character in input.uppercased() {
            if digits.isEmpty, character.isASCII, character.isLetter {
                if letters.count < maxLetters { letters.append(character) }
            } else if character.isASCII, character.isNumber {
                if letters.count >= minLetters, digits.count < digitCount { digits.append(character) }
            }
            // Separators, spaces and anything else are dropped: the hyphen is re-inserted below.
        }
        return digits.isEmpty ? letters : "\(letters)-\(digits)"
    }

    private static func isSeparator(_ scalar: Unicode.Scalar) -> Bool {
        scalar == "-" || scalar == "_" || scalar == "." || CharacterSet.whitespacesAndNewlines.contains(scalar)
    }

    private static func isASCIILetter(_ character: Character) -> Bool {
        character.isASCII && character.isLetter
    }

    private static func isASCIIUppercaseLetter(_ character: Character) -> Bool {
        character.isASCII && character.isUppercase && character.isLetter
    }

    private static func isASCIIDigit(_ character: Character) -> Bool {
        character.isASCII && character.isNumber
    }
}

/// Per-employee invite ("employee") codes, e.g. `K7PX2M`. The API accepts `[A-Z0-9-]{4,16}` (case-insensitive).
public enum EmployeeCode {
    public static let minLength = 4
    public static let maxLength = 16

    /// Trims, upper-cases and strips spaces, hyphens, underscores and dots: `k7p-x2m` → `K7PX2M`.
    public static func normalise(_ input: String) -> String {
        String(input.uppercased().unicodeScalars.filter { scalar in
            !(scalar == "-" || scalar == "_" || scalar == "." || CharacterSet.whitespacesAndNewlines.contains(scalar))
        })
    }

    public static func isValid(_ code: String) -> Bool {
        (minLength...maxLength).contains(code.count) && code.allSatisfy { $0.isASCII && ($0.isUppercase || $0.isNumber) }
    }
}
